SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(1, 'Arica', 1, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(2, 'Camarones', 1, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(3, 'General Lagos', 1, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(4, 'Putre', 1, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(5, 'Alto Hospicio', 2, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(6, 'Iquique', 2, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(7, 'Camiña', 2, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(8, 'Colchane', 2, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(9, 'Huara', 2, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(10, 'Pica', 2, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(11, 'Pozo Almonte', 2, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(12, 'Tocopilla', 3, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(13, 'María Elena', 3, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(14, 'Calama', 3, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(15, 'Ollague', 3, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(16, 'San Pedro de Atacama', 3, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(17, 'Antofagasta', 3, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(18, 'Mejillones', 3, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(19, 'Sierra Gorda', 3, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(20, 'Taltal', 3, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(21, 'Chañaral', 4, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(22, 'Diego de Almagro', 4, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(23, 'Copiapó', 4, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(24, 'Caldera', 4, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(25, 'Tierra Amarilla', 4, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(26, 'Vallenar', 4, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(27, 'Alto del Carmen', 4, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(28, 'Freirina', 4, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(29, 'Huasco', 4, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(30, 'La Serena', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(31, 'Coquimbo', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(32, 'Andacollo', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(33, 'La Higuera', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(34, 'Paihuano', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(35, 'Vicuña', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(36, 'Ovalle', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(37, 'Combarbalá', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(38, 'Monte Patria', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(39, 'Punitaqui', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(40, 'Río Hurtado', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(41, 'Illapel', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(42, 'Canela', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(43, 'Los Vilos', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(44, 'Salamanca', 5, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(45, 'La Ligua', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(46, 'Cabildo', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(47, 'Zapallar', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(48, 'Papudo', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(49, 'Petorca', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(50, 'Los Andes', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(51, 'San Esteban', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(52, 'Calle Larga', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(53, 'Rinconada', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(54, 'San Felipe', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(55, 'Llaillay', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(56, 'Putaendo', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(57, 'Santa María', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(58, 'Catemu', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(59, 'Panquehue', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(60, 'Quillota', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(61, 'La Cruz', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(62, 'La Calera', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(63, 'Nogales', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(64, 'Hijuelas', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(65, 'Valparaíso', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(66, 'Viña del Mar', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(67, 'Concón', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(68, 'Quintero', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(69, 'Puchuncaví', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(70, 'Casablanca', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(71, 'Juan Fernández', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(72, 'San Antonio', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(73, 'Cartagena', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(74, 'El Tabo', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(75, 'El Quisco', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(76, 'Algarrobo', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(77, 'Santo Domingo', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(78, 'Isla de Pascua', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(79, 'Quilpué', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(80, 'Limache', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(81, 'Olmué', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(82, 'Villa Alemana', 6, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(83, 'Colina', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(84, 'Lampa', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(85, 'Tiltil', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(86, 'Santiago', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(87, 'Vitacura', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(88, 'San Ramón', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(89, 'San Miguel', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(90, 'San Joaquín', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(91, 'Renca', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(92, 'Recoleta', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(93, 'Quinta Normal', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(94, 'Quilicura', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(95, 'Pudahuel', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(96, 'Providencia', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(97, 'Peñalolén', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(98, 'Pedro Aguirre Cerda', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(99, 'Ñuñoa', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(100, 'Maipú', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(101, 'Macul', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(102, 'Lo Prado', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(103, 'Lo Espejo', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(104, 'Lo Barnechea', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(105, 'Las Condes', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(106, 'La Reina', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(107, 'La Pintana', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(108, 'La Granja', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(109, 'La Florida', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(110, 'La Cisterna', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(111, 'Independencia', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(112, 'Huechuraba', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(113, 'Estación Central', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(114, 'El Bosque', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(115, 'Conchalí', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(116, 'Cerro Navia', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(117, 'Cerrillos', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(118, 'Puente Alto', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(119, 'San José de Maipo', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(120, 'Pirque', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(121, 'San Bernardo', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(122, 'Buin', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(123, 'Paine', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(124, 'Calera de Tango', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(125, 'Melipilla', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(126, 'Alhué', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(127, 'Curacaví', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(128, 'María Pinto', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(129, 'San Pedro', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(130, 'Isla de Maipo', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(131, 'El Monte', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(132, 'Padre Hurtado', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(133, 'Peñaflor', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(134, 'Talagante', 7, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(135, 'Codegua', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(136, 'Coínco', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(137, 'Coltauco', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(138, 'Doñihue', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(139, 'Graneros', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(140, 'Las Cabras', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(141, 'Machalí', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(142, 'Malloa', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(143, 'Mostazal', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(144, 'Olivar', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(145, 'Peumo', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(146, 'Pichidegua', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(147, 'Quinta de Tilcoco', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(148, 'Rancagua', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(149, 'Rengo', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(150, 'Requínoa', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(151, 'San Vicente de Tagua Tagua', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(152, 'Chépica', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(153, 'Chimbarongo', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(154, 'Lolol', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(155, 'Nancagua', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(156, 'Palmilla', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(157, 'Peralillo', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(158, 'Placilla', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(159, 'Pumanque', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(160, 'San Fernando', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(161, 'Santa Cruz', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(162, 'La Estrella', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(163, 'Litueche', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(164, 'Marchigüe', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(165, 'Navidad', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(166, 'Paredones', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(167, 'Pichilemu', 8, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(168, 'Curicó', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(169, 'Hualañé', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(170, 'Licantén', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(171, 'Molina', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(172, 'Rauco', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(173, 'Romeral', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(174, 'Sagrada Familia', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(175, 'Teno', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(176, 'Vichuquén', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(177, 'Talca', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(178, 'San Clemente', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(179, 'Pelarco', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(180, 'Pencahue', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(181, 'Maule', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(182, 'San Rafael', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(183, 'Curepto', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(184, 'Constitución', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(185, 'Empedrado', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(186, 'Río Claro', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(187, 'Linares', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(188, 'San Javier', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(189, 'Parral', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(190, 'Villa Alegre', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(191, 'Longaví', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(192, 'Colbún', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(193, 'Retiro', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(194, 'Yerbas Buenas', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(195, 'Cauquenes', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(196, 'Chanco', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(197, 'Pelluhue', 9, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(198, 'Bulnes', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(199, 'Chillán', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(200, 'Chillán Viejo', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(201, 'El Carmen', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(202, 'Pemuco', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(203, 'Pinto', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(204, 'Quillón', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(205, 'San Ignacio', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(206, 'Yungay', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(207, 'Cobquecura', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(208, 'Coelemu', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(209, 'Ninhue', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(210, 'Portezuelo', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(211, 'Quirihue', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(212, 'Ránquil', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(213, 'Treguaco', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(214, 'San Carlos', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(215, 'Coihueco', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(216, 'San Nicolás', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(217, 'Ñiquén', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(218, 'San Fabián', 10, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(219, 'Alto Biobío', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(220, 'Antuco', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(221, 'Cabrero', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(222, 'Laja', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(223, 'Los Ángeles', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(224, 'Mulchén', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(225, 'Nacimiento', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(226, 'Negrete', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(227, 'Quilaco', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(228, 'Quilleco', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(229, 'San Rosendo', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(230, 'Santa Bárbara', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(231, 'Tucapel', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(232, 'Yumbel', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(233, 'Concepción', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(234, 'Coronel', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(235, 'Chiguayante', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(236, 'Florida', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(237, 'Hualpén', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(238, 'Hualqui', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(239, 'Lota', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(240, 'Penco', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(241, 'San Pedro de La Paz', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(242, 'Santa Juana', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(243, 'Talcahuano', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(244, 'Tomé', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(245, 'Arauco', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(246, 'Cañete', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(247, 'Contulmo', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(248, 'Curanilahue', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(249, 'Lebu', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(250, 'Los Álamos', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(251, 'Tirúa', 11, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(252, 'Angol', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(253, 'Collipulli', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(254, 'Curacautín', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(255, 'Ercilla', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(256, 'Lonquimay', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(257, 'Los Sauces', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(258, 'Lumaco', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(259, 'Purén', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(260, 'Renaico', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(261, 'Traiguén', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(262, 'Victoria', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(263, 'Temuco', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(264, 'Carahue', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(265, 'Cholchol', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(266, 'Cunco', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(267, 'Curarrehue', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(268, 'Freire', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(269, 'Galvarino', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(270, 'Gorbea', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(271, 'Lautaro', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(272, 'Loncoche', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(273, 'Melipeuco', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(274, 'Nueva Imperial', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(275, 'Padre Las Casas', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(276, 'Perquenco', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(277, 'Pitrufquén', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(278, 'Pucón', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(279, 'Saavedra', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(280, 'Teodoro Schmidt', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(281, 'Toltén', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(282, 'Vilcún', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(283, 'Villarrica', 12, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(284, 'Valdivia', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(285, 'Corral', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(286, 'Lanco', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(287, 'Los Lagos', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(288, 'Máfil', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(289, 'Mariquina', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(290, 'Paillaco', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(291, 'Panguipulli', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(292, 'La Unión', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(293, 'Futrono', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(294, 'Lago Ranco', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(295, 'Río Bueno', 13, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(296, 'Osorno', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(297, 'Puerto Octay', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(298, 'Purranque', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(299, 'Puyehue', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(300, 'Río Negro', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(301, 'San Juan de la Costa', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(302, 'San Pablo', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(303, 'Calbuco', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(304, 'Cochamó', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(305, 'Fresia', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(306, 'Frutillar', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(307, 'Llanquihue', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(308, 'Los Muermos', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(309, 'Maullín', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(310, 'Puerto Montt', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(311, 'Puerto Varas', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(312, 'Ancud', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(313, 'Castro', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(314, 'Chonchi', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(315, 'Curaco de Vélez', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(316, 'Dalcahue', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(317, 'Puqueldón', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(318, 'Queilén', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(319, 'Quellón', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(320, 'Quemchi', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(321, 'Quinchao', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(322, 'Chaitén', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(323, 'Futaleufú', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(324, 'Hualaihué', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(325, 'Palena', 14, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(326, 'Lago Verde', 15, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(327, 'Coihaique', 15, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(328, 'Aysén', 15, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(329, 'Cisnes', 15, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(330, 'Guaitecas', 15, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(331, 'Río Ibáñez', 15, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(332, 'Chile Chico', 15, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(333, 'Cochrane', 15, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(334, 'O\'Higgins', 15, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(335, 'Tortel', 15, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(336, 'Natales', 16, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(337, 'Torres del Paine', 16, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(338, 'Laguna Blanca', 16, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(339, 'Punta Arenas', 16, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(340, 'Río Verde', 16, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(341, 'San Gregorio', 16, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(342, 'Porvenir', 16, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(343, 'Primavera', 16, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(344, 'Timaukel', 16, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(345, 'Cabo de Hornos', 16, NULL, NULL, NULL);
INSERT INTO `cities` (`id`, `cityName`, `state_id`, `created_at`, `updated_at`, `deleted_at`) VALUES(346, 'Antártica', 16, NULL, NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
